name: smart-agent-compose
services:

  memory-database:
    image: postgres:17.4
    container_name: memory-database
    environment:
      - POSTGRES_DB=memory
      - POSTGRES_USER=memory_user
      - POSTGRES_PASSWORD=memory_password
    ports:
      - "5432:5432"
