# ===============================
# GENERAL CONFIGURATIONS
# ===============================
spring:
  application:
    name: smart-agent

# ===============================
# CHAT CONFIGURATIONS (AI Model)
# ===============================
  ai:
    ollama:
      chat:
        model: ${CHAT_MODEL:gemma3}

# ===============================
# MCP CLIENT CONFIGURATIONS
# ===============================
    mcp:
      client:
        type: async
        toolcallback:
          enabled: true

# ===============================
# CHAT MEMORY (PostgreSQL)
# ===============================
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:15432}/${PG_DB:memory}
    username: ${PG_USER:memory_user}
    password: ${PG_PASSWORD:memory_password}