spring:
  application:
    name: smart-agent
  ai:
    ollama:
      chat:
        model: ${CHAT_MODEL:gemma3}
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:memory}
    username: ${PG_USER:memory_user}
    password: ${PG_PASSWORD:memory_password}