services:

  mcp-server-web-content-fetch:
    image: supercorp/supergateway-with-python
    container_name: mcp-server-web-content-fetch
    command: --stdio "python -m mcp_server_fetch"
    build:
      context: .docker/mcp-server/web-content-fetch
      dockerfile: Dockerfile
    ports:
      - "8021:8000"
